### ISSUE TITLE
fan  ls-qvl

### ISSUE THREAD

**Issue by snowdej** [1000001101000/Debian_on_Buffalo#118]
I installed sensors got a temp of around 50degrees but it said fan was 0

kirkwood_thermal-virtual-0
Adapter: Virtual device
temp1:        +48.7°C

gpio_fan-isa-0000
Adapter: ISA adapter
fan1:          0 RPM  (min =    0 RPM, max = 5000 RPM)  

I installed pwm and now i get alarm condition  - even though it says running max fans
kirkwood_thermal-virtual-0
Adapter: Virtual device
temp1:        +72.7°C

gpio_fan-isa-0000
Adapter: ISA adapter
fan1:        5000 RPM  (min =    0 RPM, max = 5000 RPM)  ALARM

This sounds a little like a closed issue I searched for when the pins were maybe inverted.

**Comment by snowdej** [comment]
I found the echo commands in the other issue
echo "5000" > /sys/devices/platform/gpio_fan/hwmon/hwmon0/fan1_target
echo "0" > /sys/devices/platform/gpio_fan/hwmon/hwmon0/fan1_target

When I set it to 5000 fan goes OFF to 0

When I set it to 0  fan goes On to Max

**Comment by snowdej** [comment]
kirkwood_thermal-virtual-0
Adapter: Virtual device
temp1:        +49.9°C

gpio_fan-isa-0000
Adapter: ISA adapter
fan1:           0 RPM  (min =    0 RPM, max = 5000 RPM)

with fan "off" temperature has dropped almost 30 degrees!

The temp sensor looks right

Is it possible that me and the other user have a reversed fan connection inside.

Mine has never been opened up - so its whatever was wired in factory

**Comment by snowdej** [comment]
I already had root enabled on my device so I renamed the /boot files and did a wget of these  (no acp_commander used)
http://ftp.debian.org/debian/dists/buster/main/installer-armel/current/images/kirkwood/network-console/buffalo/ls-qvl/

then did the ssh installer@192.x.x.x

thanks

**Comment by 1000001101000** [comment]
Yeah, that one will have the bug I described. Try the following:

1.  Download my DTB file to the device `cd /etc/flash-kernel/dtbs/; wget https://github.com/1000001101000/Debian_on_Buffalo/raw/master/Buster/device_trees/kirkwood-linkstation-lsqvl.dtb`
2.  Generate new boot files to include it `flash-kernel`
3. reboot, the fan should work as desired with that in place.

....that does remind me, there are a few other fixes I need to get into my devce tree, I'll need to find my notes. I believe I had a fix for some hotswap issues.

If your device shuts down instead of rebooting when you issue a `reboot` command I have a fix for that too.

If it's easier you could re-run with my installer which puts those in place as part of the install. Otherwise I can help you do it manually 


Am I correct that if

**Comment by snowdej** [comment]
the flash worked fine
kirkwood_thermal-virtual-0
Adapter: Virtual device
temp1:        +47.7°C

gpio_fan-isa-0000
Adapter: ISA adapter
fan1:        5000 RPM  (min =    0 RPM, max = 5000 RPM)


The manual fan setting seems not to work any more
echo "1" > /sys/devices/platform/gpio_fan/hwmon/hwmon0/pwm1_enable
bash: /sys/devices/platform/gpio_fan/hwmon/hwmon0/pwm1_enable: No such file or directory

To be honest its in a cupboard and running fan full tilt really isnt a noise issue  - might leave it without adaptive pwm controls

I had already installed the reboot tool - that worked a treat.

I am really glad to get some more years out of this device - originally being hard to ssh to and using smb it was becoming long in the tooth ... But your work has extended its life nicely - thank you so much

**Comment by 1000001101000** [comment]
Thanks!

Fancontrol should work properly now with the proper pin mappings. Personally I usually leave the fans on full unless I plan to have it right next to me all the time.
