### ISSUE TITLE
LS210D Wont boot bullseye

### ISSUE THREAD

**Issue by JoshuaSeidel** [1000001101000/Debian_on_Buffalo#160]
Did the install based on instructions, now it blinks white a bunch then goes into a loop of 7 red blinks.

how do i recover?

**Comment by 1000001101000** [comment]
Good to hear from you!

7 red blinks generally means that it failed to read the /boot partition. I would guess that something wasn't set correctly for the first/boot partition.

There are a few options for recovering:

- You could remove the drive and connect it to a PC running linux. From there you could fix any partitioning/formatting issue with /boot and copy the installer back in to try again. This model can be a pain to get the drive out and also depends on having a usb->sata adapter or PC with spare sata port etc.  
- TFTP boot the stock firmware and either re-install the firmware and start over or connect via telnet and try to correct whatever the issue is to get back to the installer etc.

When you get back to the installer partitioning menu I can verify that things look correct before proceeding if you post a screenshot,
