### ISSUE TITLE
LS-WVL can not SSH and file browser after install Webmin

### ISSUE THREAD

**Issue by khoahoc0508** [1000001101000/Debian_on_Buffalo#164]
First, thank you for the great guide to installing Debian. My ls-wvl is working perfectly, but after trying to install Webmin, I can not ssh and can not access the shared folder. I still access and config Webmin, so please help me with this situation.

Sincerely,
Trung

**Comment by 1000001101000** [comment]
Good to hear from you!

I haven't done much with Webmin. It sounds like it may have made some sort of change to your SSH config on your behalf that broke things but that is just a guess.

**Comment by khoahoc0508** [comment]
Can you give a guide on how to check and fix if the ssh and samba servers are broken?

Sincerely,
Trung

**Comment by 1000001101000** [comment]
You could try restoring sshd.conf and/or smb.conf. I could imagine the issues could also be related to file permissions (for samba shares) or user account/group membership.

“What changes did webmin make to my system and how do I undo them?” is probably a better question for the webmin folks since I know very little about webmin.

**Comment by khoahoc0508** [comment]
Thank but I can make it work again, so I reinstalled and forgot webmin.
