### ISSUE TITLE
Debian Buster on LS 220D

### ISSUE THREAD

**Issue by Rapetou** [1000001101000/Debian_on_Buffalo#81]
Hello.

I'm trying to install the package on my NAS LS220D.

When I launch the command, I'm getting the following error

 SocketTimeoutException usually indicates bad firewall settings.
Check especially for *UDP* port 22936 and make sure that the connection to your LS is working.
ERROR: Exception: SocketTimeoutException (Receive timed out) [ACP Send/Receive (Packet:80A0 = SPECIAL_CMD_EN_ONECMD)]

NAS is currently running OEM firmware version 1.75-0.05

Thanks in advance for your support

**Comment by 1000001101000** [comment]
Good to hear from you!

What command are you using when you get this?

Can you verify whether you can see the device's web interface and whether it shows up in NasNavigator/LSUpdater?

**Comment by Rapetou** [comment]
> Good to hear from you!
> 
> What command are you using when you get this?
> 
> Can you verify whether you can see the device's web interface and whether it shows up in NasNavigator/LSUpdater?

I did a cut/paste of the command line specified in your guide and made sure to enter the local IP Address.

java -jar acp_commander.jar -t 192.168.***.*** -pw ***MyPassword*** -xfer initrd.buffalo -xferto /boot/

I can reach the address (ping) and the Buffalo NAS webpage via html.

**Comment by 1000001101000** [comment]
Try ```java -jar acp_commander.jar -t ```
That will list any devices discovered on the network.

Since the device responds to ping and on the web interface we can be sure that it’s online and seems to be functional. There are a few reasons ACP commander could still have trouble communicating with it. If the above command doesn’t find anything try rebooting the device and see if that helps.

if it still can’t be seen try to connect to it with NasNavigator or lsupdater. If they don’t see it either it’s likely that the UDP broadcast packets that the protocol rely on are being blocked (mesh networks in particular tend to block them).

**Comment by lis6502** [comment]
acp_commander is known to fail with latest firmware on TS3400d, so there's big chance that LS220d's FW is also acp_commander-proof.

**Comment by 1000001101000** [comment]
known? is this documented somewhere I am unaware of?

acp commander uses the same protocol that lsupdater and NasNavigator use to communicate, I'm somewhat doubtful they've recently done anything to mess with the protocol on these older devices as it would break those tools as well. They do have two different versions of the protocol but I added support for the "newer" one over a year ago. It's possible they did something similar again but they actually have been shipping devices with both versions enabled (I think because swtiching caused them too many headaches).

If you believe that it has stopped working for a specific device/fw version please confirm whether NasNavigator/lsupdater/tsupdater working with it or not and open an issue on the acp_commander page:
https://github.com/1000001101000/acp-commander

I'll try to find some time to try out the latest version on my TS3000, if they did make such a change i might be able to do something about it. What version did you try it with?

**Comment by lis6502** [comment]
oh my, i am terribly sorry xD. I must've used some old version ( i recall it warning me, being experimental) which forced me to to find other ways to look under the hood. 
Indeed, latest version works like a breeze
```
lis6502@e595:~$  java -jar acp_commander.jar -t 172.16.32.17 -o
admin password: 
Reset root pwd...	passwd: password expiry information changed.

Starting Telnet .. Success!

You can now telnet to your box as user 'root' providing no / an empty password. Please change your root password to something secure.
lis6502@e595:~$ telnet 172.16.32.17
Trying 172.16.32.17...
Connected to 172.16.32.17.
Escape character is '^]'.

BUFFALO INC. BuffaloNas series 
UNINSPECT556 login: root
[root@UNINSPECT556 ~]# lol
-sh: lol: command not found
[root@UNINSPECT556 ~]# 
```

**Comment by 1000001101000** [comment]
Nice!

I installed the latest version for the TS3400D (v2.0 from September), it worked fine. 

@Rapetou 's issue sounds like their network might not forward udp broadcasts but that's not the only possibility. I believe I recommended rebooting which will sometimes correct the issue. If it is a "mesh network" issue you can usually plug the dive into the same switch as your PC, the packets just won't go across the mesh wifi.

**Comment by 1000001101000** [comment]
@Rapetou have you gotten a chance to look at this again?

**Comment by Rapetou** [comment]
Ho!

Sorry, I haven’t yet

I’ll try later next week and send update on results

Thanks for the follow up!

DS

**Comment by 1000001101000** [comment]
Any luck?

**Comment by sumsethan** [comment]
I'm on TS3400D fw ver.2.06 
seems like telnet can only connect to /bin/rbash
so ,to install debian I need to run commands with 'acpcommander -c xxxxx'
also works with usb boot (FAT32 part. with 2 boot files in root folder)
